version: "3.8"

services:
  app:
    build: .
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/www/amt-sleeptracker:/var/www
    expose:
      - "9000"
